--- #config file for test data collector
#database config
db_protocol:            'postgresql'
db_host:                '10.10.0.37'
db_port:                '5432'
db_name:                'mail_parser_db'
db_username:            'postgres'
db_password:            'a'

#this string overrides any other database settings
#connection_string:      'sqlite:///testdb.sqlite'

#SMTP server setup
ip_address:             '10.10.0.37'
port:                   8888
msg_ttl:                2592000
msg_ttl_enabled:        false

#logger config
log_name:               'mail_parser_log'
log_location:           '/var/log/mail_parser/mail_parser.log'
